### ISSUE TITLE
Hangfire Dashboard: Cannot implicitly convert type ‘long’ to ‘int?’. An explicit conversion exists (are you missing a cast?) 

### ISSUE THREAD

**Issue by SkippingAdi** [wanlitao/HangfireExtension#16]
Hi
We are using Hangfire 1.6.16 with SQLite 1.4.1 backend.
Whenever we click in the Dashboard on the Jobs-Tab to see the jobs lis the following exception is show:
Cannot implicitly convert type 'long' to 'int?'. An explicit conversion exists (are you missing a cast?) 

StackTrace:
[RuntimeBinderException: Cannot implicitly convert type 'long' to 'int?'. An explicit conversion exists (are you missing a cast?)]
 CallSite.Target(Closure , CallSite , Object ) +206
 Hangfire.SQLite.<>c__DisplayClass9_0.b__0(DbConnection connection) +534
 Hangfire.SQLite.SQLiteStorage.UseConnection(Func2 func, Boolean isWriteLock) +62
 Hangfire.SQLite.SQLiteJobQueueMonitoringApi.GetEnqueuedAndFetchedCount(String queue) +270
 Hangfire.SQLite.SQLiteMonitoringApi.Queues() +701
 Hangfire.Dashboard.Pages.QueuesPage.Execute() +221
 Hangfire.Dashboard.RazorPage.TransformText(String body) +31
 Hangfire.Dashboard.RazorPageDispatcher.Dispatch(DashboardContext context) +86
 Hangfire.Dashboard.<>c__DisplayClass1_2.<UseHangfireDashboard>b__1(IDictionary2 env) +466
 Microsoft.Owin.Mapping.d__0.MoveNext() +461
 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31
 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
 Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.d__5.MoveNext() +203
 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31
 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
 Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.d__2.MoveNext() +193
 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31
 Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult ar) +119
 System.Web.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +365
 System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +134

Can anybode help on this issue?
Thank you in advance
Adrian

**Comment by wanlitao** [comment]
This bug has been fixed by version 1.4.2,  please update your nuget reference
