### ISSUE TITLE
Database is locked error

### ISSUE THREAD

**Issue by arielmoraes** [wanlitao/HangfireExtension#17]
When using SQLite with a recurring job the error `SQLite error (5): database is locked` is shown in the output window many times, after that rows are inserted into the State table and they stay with the Processing state.

I'm using Hangfire in a Windows Service following the docs.

**Comment by wanlitao** [comment]
please refer to my comment on #3

**Comment by 0xced** [comment]
I have configured the background job server options with `WorkerCount = 1` but I'm still getting those errors:
```
SQLite error (5): database is locked in "select Value from [HangFire.Set] where [Key] = @key and Score between @from and @to order by Score limit 1"
```
