### ISSUE TITLE
Hi Wu, about to update hangfire extension

### ISSUE THREAD

**Issue by AJ1987** [wanlitao/HangfireExtension#26]
你好，我最近在想用hangfire的sqlite插件，找了半天网上就找到你这个extension，貌似是你自己扩展的，但是是在.net framework 4.5的版本上扩展的，然后用的System.Data.SQLite, System.Data.SQLite.EF 和 System.Data.SQLite.Linq都是基于这个版本的，我们项目现在用的是.net core 2.2的版本，我想弄个基于.net core 2.2的hangfire sqlite版本，想找你帮我看下你之前扩展的这个是在哪里加的sqlite。

万分谢谢，能不能加下我wechat:   ljp12008

**Comment by wanlitao** [comment]
不明白你的意思，现在这个支持.NETStandard 2.0平台，可以在.net core 2.2的项目中使用

**Comment by AJ1987** [comment]
> 不明白你的意思，现在这个支持.NETStandard 2.0平台，可以在.net core 2.2的项目中使用

你好，这个在。net core 2.2不能直接使用，需要安装Microsoft.EntityFrameworkCore.Sqlite才能跑通，然后运行的时候有bug，会一下子enqueue好多个job出来，但是我只建了一个job，并且workcount设置了1，不知道是什么原因导致的，然后Unit test也没有加进来呢

**Comment by wanlitao** [comment]
添加 Microsoft.Data.Sqlite 包引用就可以了
至于好多个job的问题，如果你创建的是定时job，它是在每个interval创建一个新的job执行
