### ISSUE TITLE
Maintenance needed

### ISSUE THREAD

**Issue by 0xced** [wanlitao/HangfireExtension#30]
Are you planning to release a new version with the current issues addressed?

If not, may I suggest that you invite new maintainers to help you in this task? I'd be interested to help.

**Comment by drewkill32** [comment]
I think you are going to have to fork the repo and update Hangfire's website with a link to your repo.

**Comment by 0xced** [comment]
I could do that but that wouldn't give me push access to [Hangfire.SQLite](https://www.nuget.org/packages/Hangfire.SQLite/) NuGet and I'd like to avoid creating a new NuGet package with a different identifier.

**Comment by drewkill32** [comment]
True, you could create one with a new name, they have two MySql packages listed. I'd be happy to help with the repo when needed. My company starting to use HangFire and we like the idea of using simple local storage over the overhead of SQL Server.

**Comment by felixclase** [comment]
Hi,

You can use Hangfire.LiteDB (https://github.com/codeyu/Hangfire.LiteDB) if you want to use Hangfire without the need for a database server.

In principle I was going to use this storage, but due to its inconveniences and because it is not updated, I gave up.

**Comment by 0xced** [comment]
@felixclase I actually tried LiteDB but quickly encountered db corruption: https://github.com/mbdavid/LiteDB/issues/1046 For this reason I prefer to use SQLite.

@drewkill32 It looks like forking and creating a new NuGet package will be the way forward given the lack of reply from @wanlitao for almost two years.

**Comment by mirceac71** [comment]
Hello,
I just tried the sample code and ran it twice .
Second run triggers the issue.

**Comment by felixclase** [comment]
@0xced 
I have used Hangfire.LiteDB in production without problems for months.

That mistake you found happened to you?

I collaborated with the **Hangfire.LiteDB** project for the correction of problems that did not allow me to use it in a process that I have in development, thanks to that experience I learned a lot about how Storage works in Hangfire.

If no one wants to continue with this project, they would be happy to rescue it.

**Comment by felixclase** [comment]
I will be working on a new storage in **SQLite for Hangfire**. It will not be based on this.

I will use what I learned in **Hangfire.LiteDB** to accelerate the development of this new storage.

Follow if interested:
https://github.com/felixclase/Hangfire.Storage.SQLite

**Comment by felixclase** [comment]
The repository is now in the **RaisedApp** organization (https://github.com/raisedapp/Hangfire.Storage.SQLite).

I'll see if tonight I publish the first beta of this storage.

**Comment by felixclase** [comment]
https://www.nuget.org/packages/Hangfire.Storage.SQLite/0.0.1

https://github.com/raisedapp/Hangfire.Storage.SQLite/releases/tag/0.0.1

They would help me a lot with the reporting of problems and inconveniences.

For now it is a beta, therefore I would not recommend using it in production.

**Comment by felixclase** [comment]
https://www.nuget.org/packages/Hangfire.Storage.SQLite

It is already ready to use in production.

At the moment I am using it for several processes that run every minute and so far I have not presented any inconvenience.

![image](https://user-images.githubusercontent.com/1153361/71479014-fffdff80-27c8-11ea-88b0-d440dc892da8.png)
