### ISSUE TITLE
Unable to find any use example.

### ISSUE THREAD

**Issue by SergeySagan** [wanlitao/HangfireExtension#4]
Can you please provide a "How To Use" example in your ReadMe?

**Comment by alexjamesbrown** [comment]
+1

**Comment by rocker8942** [comment]
Hey guys, I wrote a how to use example here, http://www.moneystock.net/wp_e/2016/12/03/use-hangfire-with-sqlite-in-asp-net-4-5/. Hope this help.

**Comment by umerfaruk** [comment]
It will be very useful to add this link to project description or readme.
