### ISSUE TITLE
能不能把 dapper  的依赖去掉呢  仅仅依赖sqlite自身的库

### ISSUE THREAD

**Issue by gitlsl** [wanlitao/HangfireExtension#5]
项目里用其他的orm 了从而产生了冲突呢。。我跟你同个city哈

**Comment by wanlitao** [comment]
官方的SqlServer Storage也是用的Dapper，要去掉的话工作量比较大。
Dapper这种轻量型orm侵入性比较小，与其它orm共存应该问题不大
