### ISSUE TITLE
Updated NuGet Publication

### ISSUE THREAD

**Issue by incongruousm** [wanlitao/HangfireExtension#6]
Hi, are there any plans to push @AGRocks "IF NOT EXISTS" changes out to NuGet? Just trying to decide whether to build locally or wait for a NuGet update. Thank you!

**Comment by wanlitao** [comment]
Just after merged the commit,  at the same time also push the changes to NuGet. Please download the latest version on the NuGet

**Comment by incongruousm** [comment]
The NuGet version is dated Thursday, October 22, 2015 but the changes weren't merged until Nov 25, 2015. NuGet is still providing me with a version (1.1.0) without these changes.
![hangfire sqlite commits](https://cloud.githubusercontent.com/assets/375508/14243144/ba25062e-fa4b-11e5-9c21-9886f3d97a16.png)
![hangfire sqlite nuget](https://cloud.githubusercontent.com/assets/375508/14243145/ba263864-fa4b-11e5-81d4-d8a5625a71a3.png)

**Comment by wanlitao** [comment]
Sorry, maybe at that time forgot push to NuGet. Now You can download the version 1.1.1

**Comment by incongruousm** [comment]
Thank you. :-)
