### ISSUE TITLE
support .net core?

### ISSUE THREAD

**Issue by pMonfared** [wanlitao/HangfireExtension#7]
Hello
Can you Port this Extension for .Net Core?
support .NetStandard 1.6

**Comment by wanlitao** [comment]
maybe after the .Net Core 2.0 release.

**Comment by PeterSawyer** [comment]
I second Sqlite for .net core

**Comment by bravecobra** [comment]
I've already ported it for my personal usage. I might add a PR if wanted

**Comment by dabide** [comment]
@wanlitao, .NET Core 2.0 is released. :-) Is this something you'd like to do yourself, or would a PR be welcome?

**Comment by wanlitao** [comment]
Now I'm porting to .Net Core, I will publish dotnet core version on nuget as soon as possible

**Comment by wanlitao** [comment]
Now version 1.4.0 on nuget is support .Net Core 2.0

**Comment by vhatsura** [comment]
When I tried to use Hangfire.SQLite 1.4.0 in .Net Core 2.0 project I got a following exception:
```C#
NotSupportedException: Specified method is not supported.
System.Data.Common.DbConnection.EnlistTransaction(Transaction transaction)
```
It seems that Microsoft.Data.Sqlite doesn't not support transactions yet.

**Comment by wanlitao** [comment]
@VadimGatsura you can try version 1.4.2, the problem should be solved

**Comment by vhatsura** [comment]
@wanlitao version 1.4.2 works fine. Thanks!
