### ISSUE TITLE
Records in JobParameter and State table are not deleted when expired

### ISSUE THREAD

**Issue by rocker8942** [wanlitao/HangfireExtension#8]
Hi Wanlitao, 

I expected that records in JobParameter and State is to be deleted when expired job deleted becase there is a foreign key to job table, But, it didn't. 

Any idea why? 

Regards
Joe

**Comment by wanlitao** [comment]
as the create table sql not set foreign key delete cascade

**Comment by rocker8942** [comment]
Thanks for the answer. Any reason why you didn't set foreign key delete cascade?
